---
title: "EDA Lab Assignment"
author: "Aaliyah Phillips"
date: "2026-04-28"
output: html_document
---

```{r}
# visuale the distribution of weights (carat) of ~54,000 diamonds from the diamonds dataset
ggplot(diamonds, aes(x = carat)) +
  geom_histogram(binwidth = 0.5)
```




```{r}
# The distribution of carat for smaller diamonds.
smaller <- diamonds |> 
  filter(carat < 3)
ggplot(smaller, aes(x = carat)) +
  geom_histogram(binwidth = 0.01)
```




```{r}
#When you have a lot of data, outliers are sometimes difficult to see in a histogram
ggplot(diamonds, aes(x = y)) + 
  geom_histogram(binwidth = 0.5)
#To make it easy to see the unusual values, we need to zoom to small values of the y-axis with coord_cartesian()
ggplot(diamonds, aes(x = y)) + 
  geom_histogram(binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 50))
```


```{r}
# price of a diamond varies with its quality (measured by cut) using geom_freqpoly()
ggplot(diamonds, aes(x = price)) + 
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```
```{r}
# make the comparison easier we need to swap what is displayed on the y-axis. Instead of displaying count, we’ll display the density
ggplot(diamonds, aes(x = price, y = after_stat(density))) + 
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```



```{r}
# use side-by-side boxplots to explor relationship between cut and price
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_boxplot()
```

